billsystem/billsystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('oursite.urls')),
    path('admin/', admin.site.urls)
]

billsystem/oursite/urls.py
from . import views
from django.urls import path
app_name='oursite'
urlpatterns=[
    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('addstock',views.addStock,name='addStock'),
    path('removestock',views.removeStock,name='removeStock')
]

billsystem/oursite/models.py
from django.db import models
from django.utils import timezone
class Stock(models.Model):
    Product_Name=models.CharField(max_length=100)
    Recently_Updated=models.DateTimeField('date Updated')
    Date_Added=models.DateTimeField('date Added')
    No_of_stocks=models.IntegerField(default=0)
    def __str__(self) -> str:
        return self.Product_Name+" - No of Stocks "+str(self.No_of_stocks)

billsystem/oursite/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User, auth
from .models import Stock

def home(request):
    if User.is_authenticated:
        Latest_Added_Stock=Stock.objects.order_by('-Recently_Updated')[0]
        if Latest_Added_Stock==None:
            return render(request,'oursite/home.html',dict())
        else:
            return render(request,'oursite/home.html',{'Last_Stock':Latest_Added_Stock})
    return render(request,'oursite/home.html',dict())
    # return HttpResponse("Hello Wolrd")
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request, user)
            print('Authenticated')
            return redirect("/")
        else:
            return render(request,'oursite/login.html',{"error_message":"Invalid Credentials"})
    else:
        return render(request,'oursite/login.html',dict())
    #return HttpResponse("This is a Login Page")
def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        password1=request.POST['password']
        password2=request.POST['password1']
        if User.objects.filter(username=username).exists():
            return render(request,"oursite/register.html",{'error_message':"User already Exists"})
        elif password1!=password2:
            return render(request,"oursite/register.html",{'error_message':"Password Mismatched"})
        else:
            user=User.objects.create_user(username=username,password=password1,first_name=first_name,last_name=last_name)
            user.save()
            return redirect("oursite:home")
    else:
        return render(request,template_name = "oursite/register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')
def addStock(request):
    if User.is_authenticated:
        if request.method == 'POST':
            product_name=request.POST['product_name']
            No_of_Stocks=request.POST['no_of_stocks']
            New_Stock=Stock(Product_Name=product_name,No_of_stocks=No_of_Stocks,Date_Added=timezone.now(),Recently_Updated=timezone.now())
            New_Stock.save()
            #redirect(reverse('oursite:home', kwargs={'stock_data':"Stock Added Succesfully"}))
            # return HttpResponseRedirect(reverse('oursite:results', args=(question.id,)))
            return redirect("/",{'stock_data':"Stock Added Succesfully"})
            # return render(request,'oursite/home.html',{'stock_data':"Stock Added Succesfully"})
        return render(request,'oursite/addStock.html',dict())
    else: 
        return render(request,"oursite/register.html",{'error_message':"Login pannala bro neenga!"})
def removeStock(request):
    if request.method=='POST':
        try:
            Selected_Stock_id=request.POST['stock']
            #selected_stock=Stock.get(Product_Name="stock")
        except:
            Stocks=Stock.objects.all()
            return render(request,"oursite/removeStock.html",{'Stocks':Stocks,'error':"select a Stock"})
        else:
            Stock_To_Be_Removed=Stock.objects.get(id=Selected_Stock_id)
            Stock_To_Be_Removed.delete()
            return redirect('/')
    Stocks=Stock.objects.all()
    return render(request,"oursite/removeStock.html",{'Stocks':Stocks})

billsystem/oursite/templates/oursite/addStock.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>  
    <div class="navbar"></div>
    <ul class="options">
      <a href="{%url 'oursite:home' %}"><li>Home</li></a>
    {%if user.is_authenticated%}
      <li>Hello, {{user.first_name  }}</li>
      <a href="{%url 'oursite:logout' %}"><li>Logout</li></a>
    {%else%}
      <a href="{%url 'oursite:login' %}"><li>Login</li></a>
      <a href="{%url 'oursite:register' %}"><li>Register</li></a>
    {%endif%}
      <a href="#"><li>Help</li></a>
    </ul>
    {%if user.is_authenticated%}
      <form method="POST" action="addstock">
        {% csrf_token %}
        {{stock_data}}<br>
        Product Name: <input type="text" name="product_name"  autocomplete="off"><br><br>
        No Of Stocks: <input type="number" name="no_of_stocks"  autocomplete="off"><br>
        <input type="submit" value="addstock" style="width: fit-content; background-color: #ADD8E6;">
    </form>
    {% endif %}
  </body>
</html>

billsystem/oursite/templates/oursite/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>  
    <div class="navbar"></div>
    <ul class="options">
      <a href="{%url 'oursite:home' %}"><li>Home</li></a>
    {%if user.is_authenticated%}
      <li>Hello, {{user.first_name  }}</li>
      <a href="{%url 'oursite:logout' %}"><li>Logout</li></a>
    {%else%}
      <a href="{%url 'oursite:login' %}"><li>Login</li></a>
      <a href="{%url 'oursite:register' %}"><li>Register</li></a>
      <a href="/admin">admin</a>
    {%endif%}
      <a href="#"><li>Help</li></a>
    </ul>
    {%if user.is_authenticated%}
      <a href="{% url 'oursite:addStock' %}">Add Stock</a><br>
      <a href="{% url 'oursite:removeStock' %}">Remove Stock</a>
      {%if stock_data%}
        {{stock_data}}
      {% endif %}
    {% endif %}
    <br>
    {% if Last_Stock %}
        Last Added Stock - {{Last_Stock.Product_Name}}  {{Last_Stock.No_of_stocks}}
    {% endif %}
  </body>
</html>

billsystem/oursite/templates/oursite/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="navbar"></div>
    <ul class="options">
      <a href="{%url 'oursite:home' %}"><li>Home</li></a>
      <a href="{%url 'oursite:login' %}"><li>Login</li></a>
      <a href="{%url 'oursite:register' %}"><li>Register</li></a>
      <a href="#"><li>Help</li></a>
    </ul>
    <b> 
        {{error_message}}
    </b>
    <form method="POST" action="login">
        {% csrf_token %}
        User Name: <input type="text" name="username"><br><br>
        Password: <input type="password" name="password"><br>
        <input type="submit" value="login" style="width: fit-content; background-color: green;">
    </form>
  </body>
</html> 

billsystem/oursite/templates/oursite/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>  
    <div class="navbar"></div>
    <ul class="options">
      <a href="{%url 'oursite:home' %}"><li>Home</li></a>
      <a href="{%url 'oursite:login' %}"><li>Login</li></a>
      <a href="{%url 'oursite:register' %}"><li>Register</li></a>
      <a href="#"><li>Help</li></a>
    </ul>
    {% block content %}
        <br>
        <b> 
            {{error_message}}
        </b>
        <form method="POST" action="register">
            {% csrf_token %}
            User name<br><input type="text" name="username"><br>
            First Name<br><input type="text" name="first_name"><br>
            Last Name<br><input type="text" name="last_name"><br>
            Password<br><input type="password" name="password"><br>
            Confirm Password<br><input type="password" name="password1"><br>
            <input type="submit" name="submit" placeholder="submit"><br>
        </form>
        If you already have an account <a href="/login"><strong>login</strong></a> instead.
    {% endblock %}
 </body>
</html>

billsystem/oursite/templates/oursite/removeStock.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>  
    <div class="navbar"></div>
    <ul class="options">
      <a href="{%url 'oursite:home' %}"><li>Home</li></a>
    {%if user.is_authenticated%}
      <li>Hello, {{user.first_name  }}</li>
      <a href="{%url 'oursite:logout' %}"><li>Logout</li></a>
    {%else%}
      <a href="{%url 'oursite:login' %}"><li>Login</li></a>
      <a href="{%url 'oursite:register' %}"><li>Register</li></a>
    {%endif%}
      <a href="#"><li>Help</li></a>
    </ul>
    {%if user.is_authenticated%}
      <form method="POST" action="removestock">
        {% csrf_token %}
        <label for="stock">Select the Stock to remove</label>
        <select name="stock" id="stock">
            {% for stock in Stocks %}
                <option value="{{stock.id}}">{{stock.Product_Name}}</option>
            {% endfor %}
        </select>
        <br><br>
        <input type="submit" value="remove" style="width: fit-content; background-color: #ADD8E6;">
    </form>
    {% endif %}
  </body>
</html>